### PR TITLE
Fix the qt param to use offset time

### PR DESCRIPTION
**Pull request by philipwalton**
R: @jeffposnick @addyosmani @wibblymat @gauntface

The [`qt`](https://devsite.googleplex.com/analytics/devguides/collection/protocol/v1/parameters#qt) param for the Measurement Protocol accepts a time offset, not a timestamp. Unfortunately this means hits replayed by the current version of this library are most likely being discarded (sorry for not catching this in my initial review).

### CODE REVIEW

**Comment by ithinkihaveacat** [comment]
Is it possible to record whether a hit occurred online or offline? That would be an interesting stat, and would also help verify that the code is working as expecting.

**Comment by jeffposnick** [comment]
Oops! Thanks for catching that, @philipwalton!

**Comment by jeffposnick** [comment]
(The Travis CI failures are due to the Firefox 48 rollout. I need to move the testing infrastructure to a newer version of `sw-testing-helpers` that supports https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver)

**Comment by jeffposnick** [comment]
Actually, the `replay-queued-requests` test failed due to a now-incorrect assumption about the `qt=` parameter would be. (The fact that the Firefox tests are *also* failing made that hard to recognize.)

@philipwalton, I'll update that test logic in a follow-up PR.

**Comment by jeffposnick** [comment]
@ithinkihaveacat, you can do what you suggested via adding in a custom dimension via [`config.parameterOverrides`](https://github.com/GoogleChrome/sw-helpers/tree/master/projects/sw-offline-google-analytics#googofflinegoogleanalyticsinitialize).

**Pull request merged**
