### PR TITLE
Glob directory

### LINKED ISSUE #451: sw-build always copy sw-lib in root-directory, does not consider dest key
**Library Affected**:
*sw-build*

**Browser & Platform**:
All

Currently if the I do sw-build something like:

```js
 swBuild.generateSW({
   rootDirectory: '/folderA',
   dest: '/myserviceworker.js'
 });
```

This ends up copying `sw-lib-0.18.0.min.js` into "/folderA" and "myserviceworker" at the right place.
But the "myserviceworker.js" still has code

```js
  importScripts('sw-lib.v0.0.18.min.js');
```

which should have been 

```js
  importScripts('/folderA/sw-lib.v0.0.18.min.js');
```

### PR DESCRIPTION
**Pull request by gauntface**
R: @jeffposnick @addyosmani @prateekbh 

Fixes #451 #453 

This makes a few changes:
- rootDirectory is now globDirectory
- dest must now be a full path for the output file
- swFile is now swPath and is seperate from anything else.

This actually sanitzed a lot of logic which is normally a good sign that the API is a better way to go.

Let me know what you think (Prateek I changed the swFile to swPath in the plugin, please let me know if that's not ok).

### CODE REVIEW

**Comment by jeffposnick** [comment]
Sorry for not bringing this up when we were discussing in the issue tracker, but looking at the code changes in context in this PR, I realize that we could get some additional naming equivalence if we used `swSrc` and `swDest`, or `swSrcPath` and `swDestPath`.

What do you think about that, @gauntface?

**Comment by gauntface** [comment]
I'd probably be on the side of `swSrc` and `swDest` if we went with this. @addyosmani @prateekbh does that sound like a good idea for you for the injectManifest() function?

**Comment by addyosmani** [comment]
I'm in favor of going for `swSrc` and `swDest`. Shall we go ahead with that?

**Comment by addyosmani** [comment]
Per meeting today, let's do it.

**Pull request merged**
