### PR TITLE
Build/linting fixes for sw-build-webpack-plugin

### PR DESCRIPTION
**Pull request by jeffposnick**
R: @prateekbh @addyosmani @gauntface

There are some linting errors in `sw-build-wepback-plugin` that prevent the `gulp test` portion of the `npm run publish-release` process from completing. This fixes those errors.

(I'm not sure why those errors weren't flagged in Travis CI to begin with?)

### CODE REVIEW

**Comment by prateekbh** [comment]
oh thanks so much :)
does these errors get caught in gulp lint?

**Comment by jeffposnick** [comment]
They do. I see what's going on with Travis CI, now—we need to modify `.travis.yml` to pick up the new project. I'll do that with an additional commit in this PR. Stay tuned...

**Comment by jeffposnick** [comment]
Now that we've gotten past the linting on Travis, the actual mocha tests for `sw-build-webpack-plugin` are failing: https://travis-ci.org/GoogleChrome/sw-helpers/jobs/225256553#L608

I'll sync up with @prateekbh about that.

**Comment by jeffposnick** [comment]
I'll rebase/merge against https://github.com/GoogleChrome/sw-helpers/pull/450 once that's merged and see if that fixes the test errors.

**Pull request merged**
