### PR TITLE
Latest syntax/interface updates

### PR DESCRIPTION
**Pull request by jeffposnick**
R: @addyosmani @gauntface

Here's a bunch of changes needed to match the latest specification for `sw-broadcast-cache-update`, `sw-routing`, and `sw-runtime-caching`.

I'm sure that `eslint` isn't happy with these changes. Once this is merged, I'll focus on cleaning up the formatting and adding JSDocs. (I'm avoiding that while there's still uncertainty about whether any of the interfaces need to change.)

The following sample service worker code works(!) and shows off what the current syntax looks like. Hopefully that matches everyone's understanding of where we're at.

```js
const requestWrapper = new goog.runtimeCaching.RequestWrapper({
  cacheName: 'text-files',
  behaviors: [
    new goog.broadcastCacheUpdate.Behavior({channelName: 'cache-updates'})
  ]
});

const route = new goog.routing.RegExpRoute({
  regExp: /\.txt$/,
  handler: new goog.runtimeCaching.StaleWhileRevalidate({requestWrapper}),
});

const router = new goog.routing.Router();
router.registerRoute({route});
router.setDefaultHandler({handler: new goog.runtimeCaching.NetworkFirst()});
```

(The code looks a lot nicer when used with ES2015 module imports, since you can ditch the `goog.*` namespaces.)

### CODE REVIEW

**Comment by jeffposnick** [comment]
(The `CacheWrapper` => `RequestWrapper` changes are incoming.)

**Comment by jeffposnick** [comment]
Okay, the commits with the RequestWrapper changes are in.

**Comment by addyosmani** [comment]
> Okay, the commits with the RequestWrapper changes are in.

Excellent!

**Comment by gauntface** [comment]
Lint all the things meme.

**Comment by jeffposnick** [comment]
Linted! No JSDoc yet, but I'll do that post-merge.

**Comment by jeffposnick** [comment]
I'm going to assume that this is safe to merge now. If there's anything else that you wanted to see changed, I'll roll it up into the next PR. (Which will focus on the missing JSDocs.)

**Pull request merged**
