### PR TITLE
Explicitly set `redirect: follow` when precaching

### PR DESCRIPTION
**Pull request by jeffposnick**
R: @addyosmani @gauntface

See https://github.com/GoogleChrome/sw-precache/pull/233

The same thing should apply here.

### CODE REVIEW

**Comment by gauntface** [comment]
@jeffposnick Would you be willing to write a test to confirm this behaviour doesn't revert in the future?

**Comment by gauntface** [comment]
Going to merge and write one as I have some extra time :)

**Comment by jeffposnick** [comment]
I am going to write a test one of these days. I swear!

**Comment by srosset81** [comment]
@jeffposnick for requests other than precaching, I guess we need to manually add the `{ redirect: 'follow' }` option in order to avoid the "network protocol violation". We have a few users reporting this error and I think it must be related to this problem.

**Comment by jeffposnick** [comment]
Hello @srosset81—For requests other than precaching, you can set the fetch options when configuring the strategy, as needed.

E.g. (using the v3 syntax):

```js
workbox.routing.registerRoute(
  new RegExp('/path/prefix'),
  workbox.strategies.networkFirst({
    cacheName: 'my-cache',
    fetchOptions: {
      redirect: 'follow',
    }
  })
);
```

Though as per https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch#Parameters, the default should be `'follow'`.

If you're running into trouble, and need help debugging, please open a fresh issue with reproduction details.

**Pull request merged**
