### PR TITLE
Update Readme.md - Fixed broken links

### PR DESCRIPTION
**Pull request by sethbergman**
I added the correct paths to the broken links in the Readme.

R: @jeffposnick @addyosmani @gauntface

Fixes #*issue number*

*Description of what's changed/fixed.*

*Please ensure that `gulp lint test` passes locally prior to filing a PR!*

### CODE REVIEW

**Comment by addyosmani** [comment]
Can confirm these paths are currently broken. It would be useful to check with @gauntface if the current README is being automatically generated before landing this change in case we need to make it elsewhere.

**Comment by sethbergman** [comment]
I'm wondering if these pages could be the culprit(s).

- [/templates/README.hbs](https://github.com/GoogleChrome/sw-helpers/blob/master/templates/README.hbs)

- [/jsdoc.conf](https://github.com/GoogleChrome/sw-helpers/blob/master/jsdoc.conf)

**Comment by gauntface** [comment]
Yeah, sorry, you need to use the gulp documentation task to update the templates for the readme's.

In this case it'll be edit README.hbs, run gulp documentation and commit the changes.

**Comment by jpmedley** [comment]
Those are actually not the intended paths. 

Also, since we moved the docs into another repo this isn't the right place to make the changes either.

**Comment by gauntface** [comment]
I'm afraid things have moved to a point where this PR can't be used. I'll be changing the readme's in a seperate PR.

**Comment by sethbergman** [comment]
Sounds good. Thanks for the updates.

**Pull request closed without merging**
