### PR TITLE
package.json dependency version bumps

### PR DESCRIPTION
**Pull request by jeffposnick**
R: @addyosmani @gauntface

Bumps up some of the versions of the packages we depend on. Primary goal is to pick up the latest testing helpers, but the other dependencies are getting a refresh as well.

### CODE REVIEW

**Comment by jeffposnick** [comment]
Note that we're still not passing all the Firefox tests in Travis CI, but we're closer than we previously were before the updates to the libraries.

The [current error](https://travis-ci.org/GoogleChrome/sw-helpers#L1336) from Travis's build:

```sh
1) sw-appcache-behavior Test Suite End to End Caching Test (Firefox Stable) should register a service worker to control the client:
     WebDriverError: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsIMessageListenerManager.addWeakMessageListener]
      at WebDriverError (node_modules/selenium-webdriver/lib/error.js:27:5)
      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:477:11)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:388:15)
      at doSend.then.response (node_modules/selenium-webdriver/lib/http.js:330:11)
      at process._tickDomainCallback (internal/process/next_tick.js:129:7)
  From: Task: WebDriver.executeScript()
      at Driver.schedule (node_modules/selenium-webdriver/lib/webdriver.js:414:17)
      at Driver.executeAsyncScript (node_modules/selenium-webdriver/lib/webdriver.js:651:17)
      at projects/sw-appcache-behavior/test/automated-suite.js:98:40
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1303:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2731:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2714:21)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2584:27)
      at node_modules/selenium-webdriver/lib/promise.js:639:7
      at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

**Comment by gauntface** [comment]
Might be worth calling printAvailableBrowiserInfo to see what browser versions you are running against: https://googlechrome.github.io/selenium-assistant/reference-docs/stable/v1.0.0/SeleniumAssistant.html#printAvailableBrowserInfo

I think FF 48 has still caused me issues here and there.

Changes are LGTM otherwise.

**Comment by jeffposnick** [comment]
I've added the call to print out the browser info, and it's failing with Firefox 49. But it looks to be a WebDriver issue, and isn't worse than before.

**Comment by gauntface** [comment]
I wouldn't block on it if you are happy with it.

**Comment by jeffposnick** [comment]
Already merged 😄

**Pull request merged**
